console.log("Hello Winc Academy");
let name = "Yousaf";
console.log(name);
console.log(4 + 4);
console.log("4" + "4");
console.log(8 - 2);
console.log(5 * 5);
console.log(6 / 3);
console.log(7 % 4);
let age = 41;
console.log(typeof age);
age = "41";
console.log(typeof age);